import React, { useEffect, useState, useMemo } from 'react'
import { api } from '../services/api.js'
import EditParserModal from '../components/EditParserModal.jsx'

export default function ParserRegistry() {
  const [parsers, setParsers] = useState([])
  const [error, setError] = useState(null)
  const [editingParser, setEditingParser] = useState(null)
  const [deletingParser, setDeletingParser] = useState(null)
  const [testingParser, setTestingParser] = useState(null)
  const [typeFilter, setTypeFilter] = useState('all') // 'all' | 'deterministic' | 'ml_generated'
  const [busy, setBusy] = useState(false)
  const [toast, setToast] = useState(null)

  function showToast(msg, type = 'success') {
    setToast({ msg, type })
    setTimeout(() => setToast(null), 3500)
  }

  function loadParsers() {
    api
      .listParsers()
      .then(setParsers)
      .catch((e) => setError(e.message))
  }

  useEffect(() => {
    loadParsers()
  }, [])

  const filteredParsers = useMemo(() => {
    return parsers.filter((p) => {
      const isCustom = p.source_type === 'ai_generated' || p.source_type === 'ml_generated'
      if (typeFilter === 'deterministic' && isCustom) return false
      if (typeFilter === 'ml_generated' && !isCustom) return false
      return true
    })
  }, [parsers, typeFilter])

  async function handleToggleStatus(parser) {
    const nextStatus = parser.status === 'active' ? 'disabled' : 'active'
    try {
      const updated = await api.updateParser(parser.id, { status: nextStatus })
      setParsers((prev) => prev.map((p) => (p.id === parser.id ? updated : p)))
      showToast(`Parser '${parser.name}' is now ${nextStatus}.`)
    } catch (e) {
      showToast(e.message, 'danger')
    }
  }

  async function handleSaveEdit(updatedData) {
    if (!editingParser) return
    setBusy(true)
    try {
      const updated = await api.updateParser(editingParser.id, updatedData)
      setParsers((prev) => prev.map((p) => (p.id === editingParser.id ? updated : p)))
      setEditingParser(null)
      showToast(`Parser '${updated.name}' updated successfully.`)
    } catch (e) {
      showToast(e.message, 'danger')
    } finally {
      setBusy(false)
    }
  }

  async function handleConfirmDelete() {
    if (!deletingParser) return
    setBusy(true)
    try {
      await api.deleteParser(deletingParser.id)
      setParsers((prev) => prev.filter((p) => p.id !== deletingParser.id))
      showToast(`Parser '${deletingParser.name}' deleted successfully.`)
      setDeletingParser(null)
    } catch (e) {
      showToast(e.message, 'danger')
    } finally {
      setBusy(false)
    }
  }

  if (error) return <div className="panel p-4 text-sm text-danger">{error}</div>

  const countDeterministic = parsers.filter(
    (p) => p.source_type !== 'ai_generated' && p.source_type !== 'ml_generated'
  ).length
  const countML = parsers.filter(
    (p) => p.source_type === 'ai_generated' || p.source_type === 'ml_generated'
  ).length

  return (
    <div className="space-y-5">
      {/* Toast Notification */}
      {toast && (
        <div
          className={`fixed top-4 right-4 z-50 px-4 py-2.5 rounded-lg shadow-lg text-xs font-medium border transition-all ${
            toast.type === 'danger'
              ? 'bg-red-500/20 text-red-300 border-red-500/40'
              : 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40'
          }`}
        >
          {toast.msg}
        </div>
      )}

      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold text-slate-100">Parser Registry</h1>
          <p className="text-sm text-mist mt-1 max-w-2xl">
            Every active parser in ULPF — deterministic core engines and dynamic parsers
            generated by the offline Random Forest token classifier.
          </p>
        </div>

        {/* Filter Tabs */}
        <div className="flex items-center gap-1 bg-panel2 p-1 rounded-lg border border-line text-xs">
          <button
            onClick={() => setTypeFilter('all')}
            className={`px-3 py-1 rounded font-medium transition-colors ${
              typeFilter === 'all'
                ? 'bg-wire/20 text-wire'
                : 'text-mist hover:text-slate-200'
            }`}
          >
            All ({parsers.length})
          </button>
          <button
            onClick={() => setTypeFilter('deterministic')}
            className={`px-3 py-1 rounded font-medium transition-colors ${
              typeFilter === 'deterministic'
                ? 'bg-wire/20 text-wire'
                : 'text-mist hover:text-slate-200'
            }`}
          >
            Deterministic ({countDeterministic})
          </button>
          <button
            onClick={() => setTypeFilter('ml_generated')}
            className={`px-3 py-1 rounded font-medium transition-colors ${
              typeFilter === 'ml_generated'
                ? 'bg-wire/20 text-wire'
                : 'text-mist hover:text-slate-200'
            }`}
          >
            Offline ML ({countML})
          </button>
        </div>
      </div>

      <div className="panel overflow-hidden">
        <table className="w-full text-sm">
          <thead>
            <tr className="text-left text-xs text-mist border-b border-line">
              <th className="px-4 py-2.5 font-normal">Name</th>
              <th className="px-4 py-2.5 font-normal">Vendor</th>
              <th className="px-4 py-2.5 font-normal">Format</th>
              <th className="px-4 py-2.5 font-normal">Version</th>
              <th className="px-4 py-2.5 font-normal">Type</th>
              <th className="px-4 py-2.5 font-normal">Status</th>
              <th className="px-4 py-2.5 font-normal">Created</th>
              <th className="px-4 py-2.5 font-normal">Events</th>
              <th className="px-4 py-2.5 font-normal text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {filteredParsers.map((p) => {
              const isCustom = p.source_type === 'ai_generated' || p.source_type === 'ml_generated'
              return (
                <tr key={p.id} className="border-b border-line last:border-0 hover:bg-panel2/60 transition-colors">
                  <td className="px-4 py-2.5 mono text-slate-200 font-medium">{p.name}</td>
                  <td className="px-4 py-2.5">{p.vendor || '—'}</td>
                  <td className="px-4 py-2.5 text-mist">{p.format || '—'}</td>
                  <td className="px-4 py-2.5 mono text-mist">v{p.version}</td>
                  <td className="px-4 py-2.5">
                    <span className={`chip ${isCustom ? 'chip-warning' : 'chip-neutral'}`}>
                      {isCustom ? 'ML-generated' : 'deterministic'}
                    </span>
                  </td>
                  <td className="px-4 py-2.5">
                    <button
                      onClick={() => handleToggleStatus(p)}
                      className={`text-xs px-2 py-0.5 rounded-full font-medium border transition-colors ${
                        p.status === 'active'
                          ? 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30 hover:bg-emerald-500/25'
                          : 'bg-gray-500/15 text-gray-400 border-gray-500/30 hover:bg-gray-500/25'
                      }`}
                      title="Click to toggle status"
                    >
                      {p.status}
                    </button>
                  </td>
                  <td className="px-4 py-2.5 text-mist text-xs">
                    {new Date(p.created_at).toLocaleDateString()}
                  </td>
                  <td className="px-4 py-2.5 mono text-slate-300">{p.events_processed}</td>
                  <td className="px-4 py-2.5 text-right">
                    <div className="flex items-center justify-end gap-1.5">
                      <button
                        onClick={() => setTestingParser(p)}
                        className="text-xs px-2 py-0.5 rounded bg-wire/10 border border-wire/30 text-wire hover:bg-wire/20 transition-colors"
                        title="Test parser with sample log"
                      >
                        Test
                      </button>
                      <button
                        onClick={() => setEditingParser(p)}
                        className="text-xs px-2 py-0.5 rounded bg-panel2 border border-line text-slate-300 hover:text-slate-100 hover:border-wire transition-colors"
                      >
                        Edit
                      </button>
                      {isCustom ? (
                        <button
                          onClick={() => setDeletingParser(p)}
                          className="text-xs px-2 py-0.5 rounded bg-red-500/10 border border-red-500/30 text-red-400 hover:bg-red-500/20 transition-colors"
                        >
                          Delete
                        </button>
                      ) : (
                        <span
                          className="text-xs px-2 py-0.5 rounded text-mist/40 cursor-not-allowed"
                          title="Built-in core parsers cannot be deleted"
                        >
                          Delete
                        </span>
                      )}
                    </div>
                  </td>
                </tr>
              )
            })}
            {filteredParsers.length === 0 && (
              <tr>
                <td colSpan={9} className="px-4 py-8 text-center text-mist text-sm">
                  No parsers found matching this filter.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* ─── Test Parser Sandbox Modal ─── */}
      {testingParser && (
        <TestParserModal
          parser={testingParser}
          onClose={() => setTestingParser(null)}
        />
      )}

      {/* ─── Edit Parser Modal ─── */}
      {editingParser && (
        <EditParserModal
          parser={editingParser}
          busy={busy}
          onSave={handleSaveEdit}
          onClose={() => setEditingParser(null)}
        />
      )}

      {/* ─── Delete Confirmation Modal ─── */}
      {deletingParser && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="panel max-w-md w-full p-5 space-y-4 border border-line shadow-2xl">
            <div className="flex items-center gap-3">
              <div className="w-8 h-8 rounded-full bg-red-500/20 flex items-center justify-center text-red-400">
                ⚠
              </div>
              <h3 className="text-base font-semibold text-slate-100">Delete Parser</h3>
            </div>
            <p className="text-sm text-mist leading-relaxed">
              Are you sure you want to permanently delete parser{' '}
              <strong className="mono text-slate-200">{deletingParser.name}</strong>?
            </p>
            <div className="flex justify-end gap-2 pt-2">
              <button
                type="button"
                className="btn-secondary !py-1.5 !px-3 text-xs"
                onClick={() => setDeletingParser(null)}
                disabled={busy}
              >
                Cancel
              </button>
              <button
                type="button"
                className="px-3 py-1.5 rounded-md bg-red-600 hover:bg-red-500 text-white text-xs font-medium transition-colors"
                onClick={handleConfirmDelete}
                disabled={busy}
              >
                {busy ? 'Deleting…' : 'Delete Parser'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

function TestParserModal({ parser, onClose }) {
  const [sampleLog, setSampleLog] = useState(
    parser.config?.sample_log ||
    (parser.name.includes('cisco') ? '<134>Sep 11 10:32:14 FW01 %ASA-6-302013: Built outbound TCP connection 12345 for outside:192.168.1.10/443 to 8.8.8.8/443' :
     parser.name.includes('fortigate') ? 'date=2026-09-11 time=10:35:22 devname="FG01" srcip=10.0.0.5 srcport=51322 dstip=8.8.8.8 dstport=443 proto=6 action="accept" user="jdoe"' :
     parser.name.includes('linux') ? 'Sep 11 10:40:12 server01 sshd[1234]: Accepted password for admin from 192.168.1.20 port 54321 ssh2' :
     parser.name.includes('windows') ? '{"EventID": 4624, "Computer": "WIN-SERVER01", "User": "Administrator", "IpAddress": "10.0.0.15", "TimeCreated": "2026-09-11T10:45:00Z"}' :
     parser.name.includes('apache') ? '192.168.1.50 - - [11/Sep/2026:10:42:12 +0000] "GET /login HTTP/1.1" 200 1245 "-" "curl/8.0"' :
     '2026/09/11 10:51:23 AUTH-SRV LOGIN_SUCCESS user=admin src=10.20.4.15 app=portal')
  )
  const [testing, setTesting] = useState(false)
  const [testResult, setTestResult] = useState(null)
  const [error, setError] = useState(null)

  async function handleRunTest() {
    if (!sampleLog.trim()) return
    setTesting(true)
    setError(null)
    setTestResult(null)
    try {
      const res = await api.testParser(parser.id, sampleLog.trim())
      setTestResult(res)
    } catch (e) {
      setError(e.message)
    } finally {
      setTesting(false)
    }
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="panel max-w-2xl w-full p-6 space-y-4 border border-line shadow-2xl max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between border-b border-line pb-3">
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-semibold text-slate-100">Test Parser Sandbox</h3>
              <span className="mono text-xs px-2 py-0.5 rounded bg-wire/15 text-wire font-medium">
                {parser.name}
              </span>
            </div>
            <p className="text-xs text-mist mt-0.5">
              Verify how this parser interprets raw logs and maps them to Universal Schema fields.
            </p>
          </div>
          <button onClick={onClose} className="text-mist hover:text-slate-100 text-lg">
            ✕
          </button>
        </div>

        <div className="space-y-2">
          <label className="block text-xs font-medium text-slate-300">Sample Log Line</label>
          <textarea
            className="input w-full mono text-xs h-24 resize-none"
            placeholder="Enter raw log to test…"
            value={sampleLog}
            onChange={(e) => setSampleLog(e.target.value)}
          />
        </div>

        <div className="flex items-center justify-between">
          <button
            className="btn-primary !py-1.5 !px-4 text-xs font-medium"
            onClick={handleRunTest}
            disabled={testing || !sampleLog.trim()}
          >
            {testing ? 'Testing Parser…' : 'Run Test'}
          </button>
          <span className="text-[11px] text-mist">
            Runs local engine matcher & regex extractor
          </span>
        </div>

        {error && <div className="panel p-3 text-xs text-danger">{error}</div>}

        {testResult && (
          <div className="space-y-3 pt-2 border-t border-line">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span
                  className={`text-xs px-2.5 py-0.5 rounded-full font-semibold border ${
                    testResult.matched
                      ? 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30'
                      : 'bg-red-500/15 text-red-400 border-red-500/30'
                  }`}
                >
                  {testResult.matched ? '✓ Pattern Matched' : '✗ Pattern Mismatched'}
                </span>
                <span className="text-xs text-mist">
                  Confidence:{' '}
                  <strong className="text-signal">
                    {Math.round((testResult.confidence || 0) * 100)}%
                  </strong>
                </span>
              </div>
            </div>

            {testResult.fields && testResult.fields.length > 0 && (
              <div className="panel overflow-hidden border border-line">
                <div className="px-3 py-2 border-b border-line bg-panel2 text-xs font-medium text-slate-200">
                  Extracted Fields ({testResult.fields.length})
                </div>
                <table className="w-full text-xs">
                  <thead>
                    <tr className="text-left text-mist border-b border-line">
                      <th className="px-3 py-1.5 font-normal">Field</th>
                      <th className="px-3 py-1.5 font-normal">Value</th>
                      <th className="px-3 py-1.5 font-normal">Mapped To</th>
                      <th className="px-3 py-1.5 font-normal">Source</th>
                    </tr>
                  </thead>
                  <tbody>
                    {testResult.fields.map((f, i) => (
                      <tr key={i} className="border-b border-line/50 last:border-0">
                        <td className="px-3 py-1.5 mono text-slate-200">{f.field}</td>
                        <td className="px-3 py-1.5 mono text-mist max-w-xs truncate">
                          {f.value || '—'}
                        </td>
                        <td className="px-3 py-1.5 text-wire">{f.mapped_to || f.field}</td>
                        <td className="px-3 py-1.5 text-mist">{f.source || 'parsed'}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}

            {testResult.event && (
              <div>
                <div className="text-xs font-medium text-slate-300 mb-1">
                  Universal Event Normalized Preview
                </div>
                <pre className="mono text-xs bg-ink rounded-md p-3 overflow-auto max-h-48 text-slate-300">
                  {JSON.stringify(testResult.event, null, 2)}
                </pre>
              </div>
            )}
          </div>
        )}

        <div className="flex justify-end pt-2 border-t border-line">
          <button
            type="button"
            className="btn-secondary !py-1 !px-3 text-xs"
            onClick={onClose}
          >
            Close
          </button>
        </div>
      </div>
    </div>
  )
}

